---
#### Configuration Chrony & Timedatectl ####
- hosts: all
  become: yes 

  tasks:
  - name: Install Chrony daemon for CentOS.
    package:
      name: 
       - chrony
      state: latest

  
  - name: Start and Enable Chronyd service
    systemd: 
      name: chronyd
      state: started
      daemon_reload: yes
      enabled: yes
      
  

  - name: Set timezone to Europe/Madrid
    timezone:
      name: Europe/Madrid
  
  - name: Enable ntp
    command: /usr/bin/timedatectl set-ntp true

#### Disable SELinux ####
  - name: Disable SELinux
    selinux:
      state: disabled
#### Upgrade Packages and Installation Custom ####
  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Packages for using NFS features
    dnf:
      name:
        - nfs-utils
        - nfs4-acl-tools
        - wget
      state: latest

  - name: Extra Packages
    dnf:
      name:
        - vim
        - lsof
      state: latest
 
- name: Add lines en export file
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"

###CONFIG for Local
  with_items:
  - '192.168.0.3 master.ipxsistemas.com '
  - '192.168.0.4 worker01.ipxsistemas.com'
  - '192.168.0.5 worker02.ipxsistemas.com'
  - '192.168.0.6 worker04.ipxsistemas.com'

###CONFIG for Azure
#  with_items:
#  - '10.0.1.10 master.ipxsistemas.com '
#  - '10.0.1.11 worker01.ipxsistemas.com'
#  - '10.0.1.12 worker02.ipxsistemas.com'
#  - '10.0.1.13 worker04.ipxsistemas.com'
    
  
  
