---

- hosts: master
  become: yes

  tasks:

  #- name: Install Tigera Operator
  #  command: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml

  #- name: Copy Tigera Operator YAML
  #  local_action: copy content="/custom_files/tigera-operator.yaml" dest="/tmp/tigera-operator.yaml"
  #  become: no
  
  - name: Copy file with owner and permissions
    copy:
      src: ./custom_files/tigera-operator.yaml
      dest: /tmp/
      owner: maxigg
      group: maxigg
      mode: '0644'

  - name: Execute Installation Tigera Operator
    command: kubectl create -f /tmp/tigera-operator.yaml


  #- name: Copy Custom YAML to Workers
  #  local_action: copy content="/custom_files/custom-resources.yaml" dest="/tmp/custom-resources.yaml"
  #  become: no

  - name: Copy file with owner and permissions
    copy:
      src: ./custom_files/custom-resources.yaml
      dest: /tmp/
      owner: maxigg
      group: maxigg
      mode: '0644'
  
  - name: Execute Custom YAML
    command: kubectl apply -f /tmp/custom-resources.yaml