---

- name: Copy file with owner and permissions
  copy:
    src: ./custom_files/tigera-operator.yaml
    dest: /tmp/
    owner: maxigg
    group: maxigg
    mode: '0644'

- name: Execute Installation Tigera Operator
  command: kubectl create -f /tmp/tigera-operator.yaml

- name: Copy file with owner and permissions
  copy:
    src: ./custom_files/custom-resources.yaml
    dest: /tmp/
    owner: maxigg
    group: maxigg
    mode: '0644'

- name: Execute Custom YAML
  command: kubectl apply -f /tmp/custom-resources.yaml




