- name: Add the user 'Kubeadmin' with a bash shell.
  user:
    name: kubeadmin
    comment: Admin User K8s
    shell: /bin/bash
    create_home: true 
    password: "changeyourpass"  ### Change the pass
    append: yes

- name: Setup kubeconfig for kubeadmin
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/kubeadmin/.kube
    - cp -i /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
    - chown -R kubeadmin. /home/kubeadmin/

- name: Create entry sudores file
  copy:
    content: 'kubeadmin ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/kubeadmin
    mode: 0440


