---
- name: Create directory for NFS
  file:
    path: /srv/nfs
    state: directory
    owner: maxigg
    group: maxigg
    mode: 0777

- name: Enable firewalld service
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Packages for NFS 
  dnf:
    name:
      - net-tools
      - nfs-utils
    state: latest

- name: Start and Enable NFS service
  systemd: 
    name: nfs-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Add lines en export file
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
  - '/srv/nfs	10.0.1.10(rw,sync)'
  - '/srv/nfs	10.0.1.11(rw,sync)'
  - '/srv/nfs	10.0.1.12(rw,sync)'

- name: execute exportfs -r
  command: exportfs -r

- name: execute exportfs -s
  command: exportfs -s
      
- name: Allow Network Ports in Firewalld
  firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
  with_items: 
    - "nfs"
    - "rpc-bind"
    - "mountd"
