---
- name: Create directory K8s Apps yaml
  file:
    path: /tmp/k8s_apps
    state: directory
    owner: maxigg
    group: maxigg
    mode: 0777

- name: Copy YAMLs
  copy:
    src: ./k8s_apps/nginx.yaml
    dest: /tmp/k8s_apps/
    owner: maxigg
    group: maxigg
    mode: '0644'


- name: Execute Custom YAML 
  become: yes
  command: kubectl apply -f /tmp/k8s_apps/nginx.yaml

- name: Execute expose
  become: yes
  command: kubectl expose deployment nginx-deployment-custom --type=NodePort --name=nginx-443