---
- name: Create directory for Kanboard
  file:
    path: srv/nfs/var/data/config/kanboard
    state: directory
    owner: root
    group: root
    mode: 0777

- name: Create directory for Kanboard
  file:
    path: /tmp/k8s/kanboard
    state: directory
    owner: maxigg
    group: maxigg
    mode: 0777



- name: Copy file with owner and permissions
  copy:
    src: "{{item}}"
    dest: /tmp/k8s/kandboard
    owner: maxigg
    group: maxigg
    mode: '0644'
  with_items:
    - './k8s_deploys/kanboard/*'
  
    

- name: Execute Custom YAML
  command: kubectl create -f /tmp/k8s/kanboard/namespace.yaml

- name: Execute Custom YAML
  command: kubectl create -f /tmp/k8s/kanboard/persistent-volumeclaim.yaml

- name: Kanboard Config
  copy:
    src: ./k8s_deploys/kanboard/config.php
    dest: /var/data/config/kanboard/
    owner: root
    group: root
    mode: '0644'

- name: Execute Custom YAML
  command: kubectl create configmap -n kanboard kanboard-config --from-file=config.php

- name: Execute Custom YAML
  command: kubectl create -f /tmp/k8s/kanboard/deployment.yaml


- name: Execute Custom YAML
  command: kubectl create -f /tmp/k8s/kanboard/service.yaml


- name: Execute Custom YAML
  command: kubectl delete configmap -n kanboard kanboard-config
  
- name: Execute Custom YAML
  command: kubectl create configmap -n kanboard kanboard-config --from-file=config.php

- name: Execute Custom YAML
  command: kubectl patch -n kanboard deployment app -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"




  



