---

- name: Create directory K8s Apps yamñ
  file:
    path: /tmp/k8s_apps
    state: directory
    owner: maxigg
    group: maxigg
    mode: 0777

- name: Copy App K8s MySQL
  copy:
    src: ./k8s_apps/mysql-deployment.yaml
    dest: /tmp/k8s_apps/
    owner: maxigg
    group: maxigg
    mode: '0644'

- name: Copy App K8s Wordpress
  copy:
    src: ./k8s_apps/wordpress-deployment.yaml
    dest: /tmp/k8s_apps/
    owner: maxigg
    group: maxigg
    mode: '0644'

- name: Copy App K8s Wordpress
  copy:
    src: ./k8s_apps/kustomization.yaml
    dest: /tmp/k8s_apps/
    owner: maxigg
    group: maxigg
    mode: '0644'

- name: Create directory for Wordpress
  file:
    path: /srv/nfs/var/www/html
    state: directory
    owner: nobody
    group: nobody
    mode: 0777

- name: Create directory for MySQL
  file:
    path: /srv/nfs/var/lib/mysql
    state: directory
    owner: nobody
    group: nobody
    mode: 0777

#- name: Execute Custom YAML MySQL
#  command: kubectl apply -k /tmp/k8s_apps/kustomization.yaml

#- name: Execute Custom YAML MySQL
#  command: kubectl apply -k /tmp/k8s_apps/mysql-deployment.yaml

#- name: Execute Custom YAML MySQL
#  command: kubectl apply -k /tmp/k8s_apps/wordpress-deployment.yaml

- name: K8s app
  command: kubectl create deployment hello-http --image=httpd:lastest