- hosts: master
  become: yes

  tasks:
  
  - name: Copy file to Master
    copy:
      src: ./custom_files/haproxy-ingress.yaml
      dest: /tmp/
      owner: maxigg
      group: maxigg
      mode: '0644'

  - name: Execute Installation HA Proxy
    command: kubectl apply -f /tmp/haproxy-ingress.yaml
   
  - name: Execute command to know ingress ports
    command: kubectl get svc -A
    register: store
  
  - name: Store in file the output
    local_action: "copy content='{{ store.stdout }}' dest=./kubectl.txt"
    become: no

 
        

